name: Test

on:
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get public key
        run: |
          curl --request GET \
          --url https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/public-key \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
