name: Test

on:
  workflow_dispatch:

jobs:
  test_access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get install libcurl4-openssl-dev -y
          cmake .
          make -j
      - name: Show default environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "The token: $GITHUB_TOKEN"
          echo "The GitHub Actor's username is: $GITHUB_REPOSITORY_OWNER"
          echo "GitHub SHA: $GITHUB_SHA"
      - name: Get public key
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repositoryr }} \
          --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test license checker
        run: |
          ./tabbylic -i all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
