name: Test

on:
  workflow_dispatch:

jobs:
  test_access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get install libcurl4-openssl-dev -y
          cmake .
          make -j
      - name: Get public key
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }} \
          --header 'authorization: Bearer ${{ github.token }}' \
          --header 'content-type: application/json' \
      - name: test license checker
        run: |
          ./tabbylic -i all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
