name: Test

on:
  workflow_dispatch:

jobs:
  test_access:
    runs-on: ubuntu-latest
    steps:
      - name: Show default environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "The token: $GITHUB_TOKEN"
          echo "The GitHub Actor's username is: $GITHUB_REPOSITORY_OWNER"
          echo "GitHub SHA: $GITHUB_SHA"
      - name: Get public key
        run: |
          curl --request GET \
          --url https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/public-key \
          --header 'authorization: Bearer ${{ GITHUB_TOKEN1 }}' \
          --header 'content-type: application/json' \
        env:
          GITHUB_TOKEN1: ${{ secrets.GITHUB_TOKEN }}
